spring:
  redis:
    host: localhost
    port: 6379
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        # ddl-auto: update
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/subak
    username: root
    password: '0000'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


logging.level:
  #org.springframework.security: DEBUG
  org.hibernate:
    SQL: debug
    type: trace

server:
  servlet:
    session:
      tracking-modes: cookie

jwt:
  secretKey: MySecretKey123
  validityInMilliseconds: 3600000 #1시간

cloudinary:
  cloudName: dp3fl7ntb
  apiKey: 459963999871177
  apiSecret: S1kUUdE37KKjQ9WR9z9UoRqWgjc