spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/subak
    username: root
    password: '0000'

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

server:
  servlet:
    session:
      tracking-modes: cookie